#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
autoload -Uz compinit && compinit -i
autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit

export EDITOR=vim

if [ -f "/opt/homebrew/bin/brew" ]; then
  eval $(/opt/homebrew/bin/brew shellenv)
fi

if [ -d "$(brew --prefix gnu-sed)/libexec/gnubin" ]; then
  export PATH="$(brew --prefix gnu-sed)/libexec/gnubin:$PATH"
fi

if [ -d "$(brew --prefix gnu-tar)/libexec/gnubin" ]; then
  export PATH="$(brew --prefix gnu-tar)/libexec/gnubin:$PATH"
fi

. $(brew --prefix asdf)/asdf.sh

export GOPATH="$HOME/go"
if [ -d "$HOME/go/bin" ]; then
  export PATH="$HOME/go/bin:$PATH"
fi

alias g='cd $(ghq root)/$(ghq list | fzf)'

alias k=kubectl
source <(kubectl completion zsh)
compdef __start_kubectl k
export DR="--dry-run=client -oyaml"

autoload -U colors; colors

export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# The next line makes PATH unique.
typeset -U path PATH

complete -C '/opt/homebrew/bin/aws_completer' aws
