---
- name: restart_zsh
  ansible.builtin.command: echo "please run source ~/.zshrc"

- name: restart_dock
  ansible.builtin.command: killall Dock

- name: restart_finder
  ansible.builtin.command: killall Finder

- name: restart_system_ui_server
  ansible.builtin.command: killall SystemUIServer
