---
- name: Suggest reloading zsh configuration
  ansible.builtin.command: echo "please run source ~/.zshrc"

- name: Restart Dock
  ansible.builtin.command: killall Dock

- name: Restart Finder
  ansible.builtin.command: killall Finder

- name: Restart SystemUIServer
  ansible.builtin.command: killall SystemUIServer
