---
- name: Create zsh completion directory
  ansible.builtin.file:
    path: /usr/local/share/zsh/site-functions/
    mode: 0755
    state: directory
  become: true

- name: Copy docker completion
  ansible.builtin.copy:
    src: "/Applications/Docker.app/Contents/Resources/etc/{{ item.src }}"
    dest: "/usr/local/share/zsh/site-functions/{{ item.dest }}"
    mode: 0644
  loop:
    - { src: docker.zsh-completion, dest: _docker }
    - { src: docker-compose.zsh-completion, dest: _docker-compose }
  become: true
