---
- name: Create zsh completion directory
  ansible.builtin.file:
    path: /usr/local/share/zsh/site-functions/
    mode: "0755"
    state: directory
  become: true

- name: Copy docker completion
  ansible.builtin.copy:
    src: "/Applications/Docker.app/Contents/Resources/etc/docker.zsh-completion"
    dest: "/usr/local/share/zsh/site-functions/_docker"
    mode: "0644"
  become: true
