---
- git_config:
    name: user.name
    scope: global
    value: 'Naoki Oketani'

- git_config:
    name: user.email
    scope: global
    value: okepy.naoki@gmail.com

- git_config:
    name: color.ui
    scope: global
    value: 'true'

- git_config:
    name: core.editor
    scope: global
    value: vim

- git_config:
    name: pull.ff
    scope: global
    value: only

- git_config:
    name: ghq.root
    scope: global
    value: "{{ ansible_env.HOME }}/src"

# alias
- git_config:
    name: alias.dw
    scope: global
    value: 'diff -C --color-words'

# http://qiita.com/peccul/items/90dd469e2f72babbc106
- git_config:
    name: alias.graph
    scope: global
    value: "log --graph --date=short --decorate=short --pretty=format:'%Cgreen%h %Creset%cd %Cblue%cn %Cred%d %Creset%s'"

# http://qiita.com/uasi/items/70d4358c3c70c64f4261
- git_config:
    name: alias.rebase-from-mb
    scope: global
    value: "!sh -c 'git rebase -i $(git merge-base ${1:-master} HEAD)' -"
