---
- community.general.git_config:
    name: user.name
    scope: global
    value: 'Naoki Oketani'

- community.general.git_config:
    name: user.email
    scope: global
    value: okepy.naoki@gmail.com

- community.general.git_config:
    name: color.ui
    scope: global
    value: 'true'

- community.general.git_config:
    name: core.editor
    scope: global
    value: vim

- community.general.git_config:
    name: pull.ff
    scope: global
    value: only

- community.general.git_config:
    name: ghq.root
    scope: global
    value: "{{ ansible_env.HOME }}/src"
