---
- name: Git config user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: 'Naoki Oketani'

- name: Git config user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: okepy.naoki@gmail.com

- name: Git config color.ui
  community.general.git_config:
    name: color.ui
    scope: global
    value: 'true'

- name: Git config core.editor
  community.general.git_config:
    name: core.editor
    scope: global
    value: vim

- name: Git config pull.ff
  community.general.git_config:
    name: pull.ff
    scope: global
    value: only

- name: Git config ghq.root
  community.general.git_config:
    name: ghq.root
    scope: global
    value: "{{ ansible_env.HOME }}/src"
