---
# 拡張子を常に表示する
- community.general.osx_defaults:
    key: AppleShowAllExtensions
    type: bool
    value: true

# バッテリー残量の%を表示する
- community.general.osx_defaults:
    domain: com.apple.menuextra.battery
    key: ShowPercent
    type: string
    value: 'YES'
  notify: restart_system_ui_server

# Dockを左側に配置する
- community.general.osx_defaults:
    domain: com.apple.dock
    key: orientation
    value: left
  notify: restart_dock

# ウインドウをアプリケーションアイコンにしまう
- community.general.osx_defaults:
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: true
  notify: restart_dock

# 最近使ったアプリケーションをDockに表示しない
- community.general.osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: false
  notify: restart_dock

# 新規Finderウインドウで$HOMEを開く
- community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    value: PfHm
  notify: restart_finder

- community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    value: "file://{{ ansible_env.HOME }}/"
  notify: restart_finder

# 隠しフォルダや隠しファイルを表示する
- community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
  notify: restart_finder

# デフォルトはカラム表示にする
- community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    value: clmv
  notify: restart_finder

# ネットワークストレージに.DS_Storeを作成しない
- community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

# スクリーンショットの保存形式をPNGにする
- community.general.osx_defaults:
    domain: com.apple.screencapture
    key: type
    value: png
  notify: restart_system_ui_server

# スクリーンショットに影をつけない
- community.general.osx_defaults:
    domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: true
  notify: restart_system_ui_server

# スクリーンショットのプレフィックスを変更する
- community.general.osx_defaults:
    domain: com.apple.screencapture
    key: name
    value: ss_
  notify: restart_system_ui_server

# スクリーンショットの保存先を変更する
- community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    value: "{{ ansible_env.HOME }}/Pictures"
  notify: restart_system_ui_server
