---
- name: Show all extensions
  community.general.osx_defaults:
    key: AppleShowAllExtensions
    type: bool
    value: true

- name: Place dock on the left side
  community.general.osx_defaults:
    domain: com.apple.dock
    key: orientation
    value: left
  notify: restart_dock

- name: Minimiza windows to application icons
  community.general.osx_defaults:
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: true
  notify: restart_dock

- name: Not show recent applications
  community.general.osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: false
  notify: restart_dock

- name: Open $HOME in a new Finder window
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    value: PfHm
  notify: restart_finder

- name: Open $HOME in a new Finder window
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    value: "file://{{ ansible_env.HOME }}/"
  notify: restart_finder

- name: Show hidden files
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
  notify: restart_finder

- name: Set Finder's default layout to columns
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    value: clmv
  notify: restart_finder

- name: Not create .DS_Store on network storages
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

- name: Save screen capture as png format
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: type
    value: png
  notify: restart_system_ui_server

- name: Disable shadow of screen capture
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: true
  notify: restart_system_ui_server

- name: Screen capture file name prefix
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: name
    value: ss_
  notify: restart_system_ui_server

- name: Screen capture location
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    value: "{{ ansible_env.HOME }}/Pictures"
  notify: restart_system_ui_server
