---
- homebrew_cask:
    name:
      - google-cloud-sdk
    state: upgraded
    install_options: 'appdir=/Applications'

- command: gcloud components update
  register: result
  changed_when: '"All components are up to date." not in result.stderr'
