---
- homebrew_cask:
    name:
      - google-cloud-sdk
      - owasp-zap
      - pycharm-ce
      - vagrant
      - virtualbox
    state: upgraded
    install_options: 'appdir=/Applications'

# TODO: changed: false if no updates are available
- command: gcloud components update
