---
- file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - .ssh
    - .ssh/github
    - .ssh/gitlab
    - .ssh/heroku

- copy:
    src: ssh/config
    dest: "{{ ansible_env.HOME}}/.ssh/config"
